### PR TITLE
Do not crash and burn when no good target is specified when sending an email

### PR DESCRIPTION
**Pull request by emanuil-tolev**

### CODE REVIEW

**Comment by emanuil-tolev** [comment]
issue #548

**Comment by richard-jones** [comment]
Looks ok to me, and certainly good to fix this issue initially.

That said, whatever is passing a [None] in should also be sorted out at some point :)

**Comment by emanuil-tolev** [comment]
Not fault of the code @richard-jones , the account has no email set.

**Comment by richard-jones** [comment]
Yup, sure - maybe best just to handle this in app_email then, as you've done.

**Pull request closed without merging**
