### PR TITLE
add commas and spaces to APC display

### PR DESCRIPTION
**Pull request by amdomanska**
Patch for issue raised by Judith: https://github.com/DOAJ/doajPM/issues/2988

Fixed display:
multiple APCs

image

### CODE REVIEW

**Comment by sssoz** [comment]
I have seen this issue pop up before, not sure if related to the modifications in this PR: 

Screenshot 2021-06-28 at 23 35 49

--- 

As for the other changes in the TOC / journal detail page: 
- the other currencies bit should be in another sentence; "and other charges" has been broken up and should be part of the first sentence in order to make sense
- can we make sure to use the Oxford comma when necessary (it’s part of our writing rules)?
- there is an extra space before the comma
- missing a comma at the beginning of the sentence

The result should look something like this: 
> The highest fee charged by this journal is **3421 GBP** as [publication fees](url) (article processing charges or APCs) and there are [other charges](url). 
>
> In other currencies, the highest publication fee is: 
> - 2342 USD
> - 15435 EUR 

Or like this: 
> The highest fee charged by this journal is **3421 GBP** as [publication fees](url) (article processing charges or APCs) and there are [other charges](url). 
>
> The highest publication fee in other currencies is **2342 USD** or **15435 EUR**.

**Comment by amdomanska** [comment]
> I have seen this issue pop up before

Not related but worth fixing here :) I'll make sure it is fine.

**Comment by amdomanska** [comment]
image
image
image

**Comment by sssoz** [comment]
Looks great, thank you!

**Review by sssoz — APPROVED** [review]

**Review by richard-jones — APPROVED** [review]

**Review by Steven-Eardley — APPROVED** [review]

**Comment by Steven-Eardley** [comment]
merged to master as hotfix

**Pull request closed without merging**
