### PR TITLE
Hotfix/2016 03 04 acc name form

### PR DESCRIPTION
**Pull request by Steven-Eardley**
Part of the changes for #961 - allowing users (and admins) to change account's name.

### CODE REVIEW

**Comment by Steven-Eardley** [comment]
Looks like this:

screen shot 2016-03-04 at 13 55 14

**Comment by emanuil-tolev** [comment]
Does this work as-is then? No changes to the Python form objects to add .name field or whatever? Or is this just the 1st piece, like the UI.

**Comment by Steven-Eardley** [comment]
It works as-is: see lines 57 and [58](https://github.com/DOAJ/doaj/blob/develop/portality/view/account.py#L58) in accounts.py: all keys from the POST (apart from the disallowed ones) are added to the data. This probably does mean I could add my own field and data to my account if I wanted!

I verified it working in my local index - adding text to that box does add a ```.name``` attribute, and the text is retrieved on subsequent loads. Plus, it saves properly and is visible in the index.

**Comment by emanuil-tolev** [comment]
> It works as-is: see lines 57 and 58 in accounts.py: all keys from the POST (apart from the disallowed ones) are added to the data.

Hahah, what is this form handling .. it's very different to the other forms. Fair enough though!

**Pull request closed without merging**
