### PR TITLE
Hotfix/iss1030 admin fv seal

### PR DESCRIPTION
**Pull request by Steven-Eardley**
## HOTFIX

Added the seal facet and logo go admin search for journals. Added a few missing semicolons. #1030

### CODE REVIEW

**Comment by emanuil-tolev** [comment]
:+1: . Did you use some kind of JS lint to check for the style issues, like an IDE or something else?

As an aside, that's quite a nostalgic PR, I remember writing a fair bit of that JS in a hurry in Dec '13 when we were frantically trying to get it to work before its old platform shut down.

**Comment by Steven-Eardley** [comment]
Just PyCharm's JS warnings. I'm happy to release this - shall I review and merge the other backlog of @richard-jones' PRs to develop too?

**Comment by Steven-Eardley** [comment]
Either way, I've done them and released this ;)

**Comment by emanuil-tolev** [comment]
> Either way, I've done them and released this ;)

Yep, I just had time to go through them. Can't find any faults in any!

**Pull request merged**
