### PR TITLE
Feature/935 refactor history system

### PR DESCRIPTION
**Pull request by emanuil-tolev**
#935 .

Journals not done yet, see discussion in issue. #936 on the way.

### CODE REVIEW

**Comment by emanuil-tolev** [comment]
Not very complex PR @richard-jones @Steven-Eardley - welcome any thoughts. It can be merged as it is, not waiting for anything.

**Comment by emanuil-tolev** [comment]
@richard-jones @Steven-Eardley - article and journal history system has been refactored, tests pass now :). The test harness is a bit more robust when it comes to the history system now as well. The only thing missing is an archival script to S3 or Glacier and a cron job spec.

**Comment by emanuil-tolev** [comment]
However this should be ready to merge, the regular archival is by no means dependent on this

**Comment by Steven-Eardley** [comment]
Looks good

**Pull request merged**
