### PR TITLE
Changed link target on the public application form; points to publishers...

### PR DESCRIPTION
**Pull request by Steven-Eardley**
for #562

### CODE REVIEW

**Comment by Steven-Eardley** [comment]
MERGE LOCALLY

**Comment by Steven-Eardley** [comment]
@emanuil-tolev @richard-jones I'm no longer 100% sure about the release procedure for hotfixes (production? tags?), so please can someone do it :)

**Comment by emanuil-tolev** [comment]
@Steven-Eardley we've got a meeting in a bit so you can release it while I'm around

I wrote a short page on the wiki on releasing hotfixes: https://github.com/DOAJ/doaj/wiki/How-to-release-a-hotfix

**Comment by emanuil-tolev** [comment]
:+1:

**Pull request closed without merging**
