### PR TITLE
Feature/1670 reorganise toc

### PR DESCRIPTION
**Pull request by amdomanska**
Fixes: https://github.com/DOAJ/doajPM/issues/1670

### CODE REVIEW

**Comment by richard-jones** [comment]
Before reviewing the code, we should talk to the team about this and make sure that we've interpreted the functionality correctly.  I would like to put this on the test server, but I also don't want to disturb the edges/bootstrap upgrade testing, so let's talk about it in today's meeting and then decide when this can be shown.

**Comment by amdomanska** [comment]
@ClaraDOAJ 

* Information about APC/Submission Charges/Waiver policy is shown only when available
* if APC info is available url is required, information about the value and currency does not have to be included.
* Submission Charges: as APC
* Waiver policy: only url

On screenshot you can see scenarios:
1) no information available
2) only url provided for APC and Submission Charges, no information about waiver policy
3) url, value and currency provided for APC, only url provided for submission charges, waiver policy url provided

Screenshot from 2019-07-30 13-28-45
Screenshot from 2019-07-30 13-29-21
Screenshot from 2019-07-30 13-29-39

**Comment by dommitchell** [comment]
@jbarnsby this is exactly what you were talking about in the management meeting today about the 'No information' journals. Please see https://github.com/DOAJ/doajPM/issues/1670

**Comment by Steven-Eardley** [comment]
I've had a look at this, but I'm not entirely sure from the issues about the objective here. There are some remaining labels we still show on journals with missing information:

Screenshot from 2019-08-04 13-26-33

The code looks good, though - keeping this open for discussion of the objectives next meeting.

**Comment by dommitchell** [comment]
> * Information about APC/Submission Charges/Waiver policy is shown only when available
> * if APC info is available url is required, information about the value and currency does not have to be included.
> * Submission Charges: as APC
> * Waiver policy: only url

hi @amdomanska lovely to meet you, albeit virtually for the moment!

ALL questions covered here (Qus 13 through to 21) on the application form are compulsory so all answers would be completed, probably by the DOAJ Team. 

> There are some remaining labels we still show on journals with missing information:

@Steven-Eardley you are correct but when adding those URLs they do generate links on the journal home page 8https://doaj.org/toc/1415-5419 I added an editorial board link as a test to show you).
The problem with the Publication Charges section is that we changed the questions so the new style application form doesn't match up with the old style journal TOCs for some journals.

**Comment by richard-jones** [comment]
I'm currently working on the feedback from the UI review, so I can free up the test server if you want to put this up on test @Steven-Eardley @amdomanska for an easier review by the team?

**Comment by amdomanska** [comment]
@Steven-Eardley the label "no information available" is shown for old journals before these information were required. 
@dommitchell nice to meet you! All these informations must be completed in the form but not all of them are compulsory. I mean: about eg. APC the answer might be "No" with URL to additional information or "Yes" with URL and value/currency. Both will be displayed appropriately (screenshot #2 and #3)
@richard-jones I think it's good idea

**Comment by amdomanska** [comment]
It's on the branch server.

@dommitchell @ClaraDOAJ if you could check if that's what you need it would be great.

**Comment by Steven-Eardley** [comment]
I've rebased this branch (making it ready for release) and it's currently up on https://testdoaj2.cottagelabs.com for any further review

**Pull request closed without merging**
