### PR TITLE
ToC SEO

### PR DESCRIPTION
**Pull request by emanuil-tolev**
Introduce title and description meta tags for journal *and* article pages (bonus!). Keywords tag is no longer used and in fact penalized by Bing so not adding that.

Reroute all ToC pages to use ISSNs. The canonical URL is the one with the ISSN now, but an internal ES hex id will be accepted if no ISSN can be provided. Continuations should continue to work. All search results, sitemap, etc. have adopted the new approach. Finally, E-ISSNs are preferred over P-ISSNs where available.

### CODE REVIEW

**Comment by emanuil-tolev** [comment]
Issue #178 .

**Comment by emanuil-tolev** [comment]
fyi @richard-jones @Steven-Eardley , last (expected) PR for PVOD :)

**Comment by richard-jones** [comment]
When I try to visit a ToC for a journal with both print and electronic issns I get a redirect loop!

**Comment by emanuil-tolev** [comment]
Hm, I thought I took care of that. I'll double check my test data and code, thanks.

**Comment by emanuil-tolev** [comment]
Yep, I thought I had tested it but in fact had never left my test journal with both ISSNs defined.

I've got a journal like this:
pissn: 1307-4733
eissn: 6954-854X
id: e52d9e100f5147edbf65b756f1e9bab6

/toc/1307-4733 redirects to /toc/6954-854X
/toc/e52d9e100f5147edbf65b756f1e9bab6 redirects to /toc/6954-854X
/toc/6954-854X displays the ToC

all the links on the ToC itself (like issues, volumes), and in the search results are to /toc/6954-854X

**Comment by emanuil-tolev** [comment]
updated

**Comment by richard-jones** [comment]
ok, that seems to have fixed it.

**Pull request merged**
