### PR TITLE
Feature/3218 editorial todo  editor

### PR DESCRIPTION
**Pull request by richard-jones**
# Editor and Associate Editor Dashboard pages

*Please don't delete any sections when completing this PR template; instead enter **N/A** for checkboxes or sections which are not applicable, unless otherwise stated below*

See https://github.com/DOAJ/doajPM/issues/3218

This PR introduces several new features:

* An editorial dashboard page
* An associate editor dashboard page
* A change to the way that dates are presented on all todo list dashboards (including the managing editor's dashboard)

The associate editor and editor criteria for the dashboard are implemented as specified here https://docs.google.com/spreadsheets/d/1WJLsbtx3wkdNeakrnP3QkvSYls4uFw0lPPzychq7Mo4/edit#gid=0

## Categorisation

This PR...
- [ ] has scripts to run
- [ ] has migrations to run
- [ ] adds new infrastructure
- [ ] changes the CI pipeline
- [ ] affects the public site
- [x] affects the editorial area
- [ ] affects the publisher area

## Basic PR Checklist

- [ ] FeatureMap annotations have been added
- [x] Unit tests have been added/modified
- [x] Functional tests have been added/modified
- [x] Code has been run manually in development, and functional tests followed locally
- [x] No deprecated methods are used
- [x] No magic strings/numbers - all strings are in `constants` or `messages` files
- [x] ES queries are wrapped in a Query object rather than inlined in the code
- [x] Where possible our common library functions have been used (e.g. dates manipulated via `dates`)
- [x] Urls are constructed with `url_for` not hard-coded
- [x] **N/A** If needed, migration has been created and tested locally
- [x] Release sheet has been created, and completed as far as is possible https://docs.google.com/spreadsheets/d/1Bqx23J1MwXzjrmAygbqlU3YHxN1Wf7zkkRv14eTVLZQ/edit#gid=347670213&range=A2
- [x] **N/A** Documentation updates - if needed - have been identified and prepared for inclusion into main documentation (e.g. added and highlighted/commented as appropriate to this PR)
    - [x] Core model documentation: https://docs.google.com/spreadsheets/d/1lun2S9vwGbyfy3WjIjgXBm05D-3wWDZ4bp8xiIYfImM/edit
    - [x] Events and consumers documentation: https://docs.google.com/spreadsheets/d/1oIeG5vg-blm2MZCE-7YhwulUlSz6TOUeY8jAftdP9JE/edit
- [x] There has been a recent merge up from `develop` (or other base branch)
    * 2023-06-26

## Testing

The functional tests are here

https://docs.google.com/spreadsheets/d/1fT9TD4dzxNclhAB0Ax_yuoQGHBY2m2i8Cefs_8kD5Nc/edit#gid=0

To run these tests you need to use the new "testdrive" endpoint, which will set the application up for testing.  Each functional test tells you which endpoint to use, and they can be accessed by putting the url into your browser (you must be logged into DOAJ on the test machine for this to work):

https://testdoaj.cottagelabs.com/testdrive/[name of testdrive endpoint]

For example 
* https://testdoaj.cottagelabs.com/testdrive/todo_associate 
* https://testdoaj.cottagelabs.com/testdrive/todo_editor_associate
* https://testdoaj.cottagelabs.com/testdrive/todo_maned_editor_associate

The response to each of these endpoints will include a summary of the resources created, and most importantly a username/password pair for you to login as the test user.  For example:

Screenshot from 2022-11-23 14-43-46

It is recommended that you carry out the tests themselves using the credentials returned by the testdrive in a private/incognito browser, so that you can log in with the test accounts provided without logging out of the test server with your main user account.

## Deployment

There are no deployment considerations

### Configuration changes

**N/A**

### Scripts

**N/A**

### Migrations

**N/A**

### Monitoring

**N/A**

### New Infrastructure

**N/A**

### Continuous Integration

**N/A**

### CODE REVIEW

**Review by philipkcl — APPROVED** [review]

**Review by sssoz — COMMENTED** [review]
@richard-jones & @dommitchell  Just a quick comment: once a priority item gets escalated from an associate editor up to their managing editor, does it get removed from their own priority item list? This is what I am seeing but I’m not sure if it’s the intended behaviour. I think it might be counterintuitive since they would no longer be aware that their applications need urgent attention.

For example, in my dataset, I am ManEd of **Turkish 1**. The user `Ramazan` has 9 ongoing applications, as shown in my editorial activity chart, and all of them are in my priority queue as ManEd. However, when I log into `Ramazan`’s account, I get the message: 
 
Screenshot 2022-09-27 at 17 37 11

...which isn’t true at all, since they do have plenty of urgent items, we’re just not showing them anymore.

**Comment by sssoz** [comment]
> @richard-jones & @dommitchell Just a quick comment: once a priority item gets escalated from an associate editor up to their managing editor, does it get removed from their own priority item list? This is what I am seeing but I’m not sure if it’s the intended behaviour. I think it might be counterintuitive since they would no longer be aware that their applications need urgent attention.
> 
> For example, in my dataset, I am ManEd of **Turkish 1**. The user `Ramazan` has 9 ongoing applications, as shown in my editorial activity chart, and all of them are in my priority queue as ManEd. However, when I log into `Ramazan`’s account, I get the message:
> 
> Screenshot 2022-09-27 at 17 37 11
> 
> ...which isn’t true at all, since they do have plenty of urgent items, we’re just not showing them anymore.

Disregard this comment — behaviour seems to be as intended: user Ramazan (Associate Ed in Turkish 1) only had READY and COMPLETED (OLD) applications. It is normal that this user wouldn’t see either application anymore. As intended, user ltamam (Editor of Turkish 1) still does have them in their queue, as well as the Managing Editor of Turkish 1.

**Comment by sssoz** [comment]
Just one thing for me to do before we can release it is that the "Group info" tab content should go at the top of the dashboard landing (as it is in ManEd’s dashboard).

**Comment by sssoz** [comment]
This PR is ready for reviewing again after my latest commits. @richard-jones @Steven-Eardley 

Thanks!

**Pull request merged**
