### PR TITLE
Added timezone label to timestamps in file upload tables. Achieved by ad...

### PR DESCRIPTION
**Pull request by Steven-Eardley**
...ding a context processor to apply formatting from Flask.

new requirement: pytz, for timezone information. #462

### CODE REVIEW

**Comment by Steven-Eardley** [comment]
As I said in my FIXME, is there a better place to put the new context_processor?

**Comment by emanuil-tolev** [comment]
You could use a jinja filter function. See line 90 in portality.core . Feel free to define it right there - if we get enough of them they'll just go in a separate module. The way you use a filter is

{{ template_variable | filter_name }}

So for the debug one that is defined you might do

```
{# Journal ID seems to be blank but it was set in the python route that renders this template! Oh noes what is jinja doing with my value #}
{{ journal.id | debug }}
{# the above will output *nothing* to the template because the debug filter returns "", but will print the var to the log#}
```

Does that sound adequate for this use case? It's not gonna get applied to all dates automatically, obviously, but then neither is a context processor function.

**Comment by Steven-Eardley** [comment]
Well, I'm happy to do it either way. The context_processor is just a way of making my function available to the template. You're right though, the behaviour is quite filter-y so I'll rewrite it as one.

**Comment by Steven-Eardley** [comment]
I've made it a filter, but left it where it was. It's next to the other ones written for ```publisher.py```, and it's only used there for now. I also prefer the way of registering them via the blueprint. I'm not sure why.

**Comment by emanuil-tolev** [comment]
Looks good! I'd probably put it in a more general place though, like core or app or similar. Formatting dates is not something I'd like to see 2 blueprints, or any 2 parts of the app do differently from each other :). Making it more general increases the chance it will be reused in the future instead of yet another one written?

**Comment by Steven-Eardley** [comment]
Putting it in app.py meant I could still register it nicely, so smiles all round.

**Comment by emanuil-tolev** [comment]
Cool, let's try it on test!

(BTW the above was just an opinion, if you really feel like it's better off in the publisher view, feel free to put it there.)

**Comment by Steven-Eardley** [comment]
I think we found the best solution! :rainbow: collaboration :rainbow:

**Comment by emanuil-tolev** [comment]
oh god the c-word :D

**Pull request merged**
