### PR TITLE
fix bug where missing dois or fulltexts in an incoming article batch …

### PR DESCRIPTION
**Pull request by richard-jones**
…caused import failure due to incorrectly identified duplicates

### CODE REVIEW

**Comment by Steven-Eardley** [comment]
Changes look sane; when I ran tests I had an intermittent bug on one of the parameterised tests involving the lock - there could be a race condition in there somewhere. Something to look out for, but not blocking.

**Comment by richard-jones** [comment]
Cool, can we get this merged and deployed asap?

**Comment by Steven-Eardley** [comment]
And another test failure from running this branch, different to the last. I'll consider these unrelated and run the release now.

```
Failure
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/unittest/case.py", line 331, in run
    testMethod()
  File "/Users/steve/code/cl/doaj/lib/python2.7/site-packages/parameterized/parameterized.py", line 392, in standalone_func
    return func(*(a + p.args), **p.kwargs)
  File "/Users/steve/code/cl/doaj/src/doaj/doajtest/unit/test_bll_accept_application.py", line 127, in test_01_accept_application
    assert app_prov is not None
AssertionError: 
```

**Comment by Steven-Eardley** [comment]
Released 2019-02-27

**Pull request closed without merging**
