### PR TITLE
Data model improvements

### PR DESCRIPTION
**Pull request by amdomanska**
Work on https://github.com/DOAJ/doajPM/issues/2899

### CODE REVIEW

**Comment by amdomanska** [comment]
>admin.last_manual_update exists but doesn't appear to be used. There is also last_manual_update. Check that the admin one isn't valid anywhere, and then remove it from the models (I don't believe any data is stored in the index in this field)

I haven't found any applications or journals with `admin.last_manual_update` populated with data nor any usage for this field in the code. Field removed from the `application` model.

**Comment by amdomanska** [comment]
>last_reapplication field is obsolete, I believe

I haven't found any records where this field exists. In the code it is only used multiple times in the `portality/migrate/20180106_1463_ongoing_updates/sync_journals_applications.py`. I'm removing this field from the model.

**Comment by amdomanska** [comment]
>  In the journal CSV there are a variety of ways that we join lists, | ; , - should we try to standardise
https://github.com/DOAJ/doajPM/issues/2899#issuecomment-835829848

**Comment by amdomanska** [comment]
> licence_display is a list which takes a value "Embed" as a single element. This is a hang-over from a late-stage course change on the application form that is patched at the view layer to be a straight True/False, but in the model is not. If possible we should refactor the model to be in line with how this data is entered and viewed

I refactored that in code:
```
"fields" : {
                        "license_display" : {"coerce" : "unicode", "allowed_values" : ["Embed", "Display", "No"]},
```
@Steven-Eardley does it require some changes in es configuration?

**Comment by Steven-Eardley** [comment]
closing this PR as superseded (keeping the branch)

**Pull request closed without merging**
