### PR TITLE
Feature/facets

### PR DESCRIPTION
**Pull request by richard-jones**
This is a first pass on the new public search facets, implementing what I suggest in #539 .

Now that a general approach to enabling/disabling facets has been developed, depending on what other filters are selected, we can easily change things around.

In the mean time, we should merge this to develop so that it goes out to the test server, and can be reviewed.

### CODE REVIEW

**Comment by emanuil-tolev** [comment]
> In the mean time, we should merge this to develop so that it goes out to the test server, and can be reviewed.

No test server exists just now and it's not been quite set up. @richard-jones do we need to consider running ES1.4 on yours while @markmacgillivray and I iron out the snags in the new infrastructure?

**Comment by richard-jones** [comment]
I've just added some more code to this branch which handles link shortening.

bitly requires oauth credentials for shortening, so there is a back-end method which proxies for the bitly api, and which constrains the scope of the urls that can be shortened to the doaj search queries only.

In production, this is going to require an oauth token that belongs to the DOAJ's bitly account; for the time being I'm using my own one in testing, and will share that for the test server.

**Comment by richard-jones** [comment]
I'm just adding new search interface enhancements to this branch, until it gets merged.  Latest changes normalise usage of Subject/Classification/Keywords across all search interfaces (with special treatment for the public interface).

**Comment by richard-jones** [comment]
This next commit causes the page to scroll to the top when the next/previous buttons are used

**Comment by richard-jones** [comment]
This one adds a new pager to all the facetviews

**Comment by emanuil-tolev** [comment]
OK, let's see this go on http://doaj.cottagelabs.com !

**Pull request merged**
