### PR TITLE
Expand form fields in modals & ed. side panel

### PR DESCRIPTION
**Pull request by sssoz**
& Increase width of modals in general

See DOAJ/doajPM#3136 and DOAJ/doajPM#2904

### CODE REVIEW

**Review by amdomanska — APPROVED** [review]

**Comment by sssoz** [comment]
Sorry @amdomanska, saw you already reviewed & approved; I just made more minor visual updates now

**Review by richard-jones — APPROVED** [review]
Code looks good to me.  Since it is changing the editorial application forms, do we need this up onto test before release?

**Comment by sssoz** [comment]
@richard-jones yeah I think that is probably wise! Let me know once it's up on test.

**Comment by Steven-Eardley** [comment]
Superseded, closing

**Pull request closed without merging**
