### PR TITLE
[hotfix] make sure index is initialised even when running via gunicorn

### PR DESCRIPTION
**Pull request by emanuil-tolev**
#1341 fix

(don't deploy yet, moving buckets on live)

### CODE REVIEW

**Comment by Steven-Eardley** [comment]
Yeah, well because I merged my associate privileges pull request it'll be a pain release this anyway...

**Comment by emanuil-tolev** [comment]
> Yeah, well because I merged my associate privileges pull request it'll be a pain to release this anyway...

Hah, yes, that's why I was thinking of just merging that to develop.

**Comment by emanuil-tolev** [comment]
Actually, I wonder whether we should revert the associate privileges merge commit from production. It will remain on develop, and you've given instructions to test it. Then, when it's time to deploy it live, we just revert the revert commit and it will be back in again.

That would enable us to deploy this ^ and any other hotfixes necessary in the meantime.

**Comment by Steven-Eardley** [comment]
Okay, it took me a while and learning about ```git gc```, but I managed to merge this and revert my boo-boo on ```production```.

**Comment by Steven-Eardley** [comment]
Deployed to live.

**Pull request closed without merging**
