### PR TITLE
Turn off autosuggestion on new application form

### PR DESCRIPTION
**Pull request by amdomanska**
Fixes https://github.com/DOAJ/doajPM/issues/2211

### CODE REVIEW

**Comment by amdomanska** [comment]
> I'm curious as to why there's an extra input field; shouldn't disabling for the whole form be enough?

A few older browsers support `autosuggestion=off` only for input field.

**Comment by amdomanska** [comment]
> Which if any of these fields https://www.w3.org/TR/WCAG21/#input-purposes is currently being mistaken?

The problem is mainly with URL for Open Access Statement and Platform I believe.

**Comment by amdomanska** [comment]
> Also, according to https://developer.mozilla.org/en-US/docs/Web/Security/Securing_your_site/Turning_off_form_autocompletion, we will also lose the local cache of filled fields, which could be annoying if e.g. a user accidentally clicks back then wants to go forward again to the form.

Good point. I believe @dommitchell needs to decide what's more important.

**Comment by amdomanska** [comment]
@richard-jones I'm not sure if it matters but it think it was meant to be for application form only
https://github.com/DOAJ/doajPM/issues/2211#issuecomment-552799163

**Comment by dommitchell** [comment]
> we will also lose the local cache of filled fields, which could be annoying if e.g. a user accidentally clicks back then wants to go forward again to the form.

I think that this would be *really* annoying actually. Can we hold off on this one until we can discuss it or is that tricky?

**Comment by amdomanska** [comment]
@richard-jones your solution works with cache fine, right?

**Comment by richard-jones** [comment]
>>we will also lose the local cache of filled fields, which could be annoying if e.g. a user accidentally clicks back then wants to go forward again to the form.

> I think that this would be really annoying actually. Can we hold off on this one until we can discuss it or is that tricky?

In my testing I didn't have any issues with the page caching, and I'm not sure how autocomplete as a user feature and "remembering what the user typed into the form" are the same. I suspect this concern is just the product of some dodgy online documentation somewhere.  All my research online about this hasn't turned up any explicit link between those two features.

I'll hold off until you give the go ahead, and if you want we can put it up on test so you can try it out first.

**Comment by Steven-Eardley** [comment]
I've put this up on test as the branch `feature/2019-11-27_application_form_autocomplete` (because this branch is python2)

I'm seeing the issue I expected above - on the live site, you can part-edit the form, hit back in the browser, and then forward and your unsubmitted form is still there. This no longer happens on the test server.

**Comment by Steven-Eardley** [comment]
I've now reinstated `develop` on the test server for the sake of the upcoming demo.

**Comment by richard-jones** [comment]
This issue looks contentious, and also subject to differing whims of the browser manufacturers.  Reading this page https://www.w3.org/WAI/WCAG21/Understanding/identify-input-purpose.html it suggested that you could specify autocomplete fields where they are relevant, but the problem we're having is that FFX and Chrome (and others?) are assuming fields should be autocompleted when they shouldn't be.

I also don't get the caching issue in Chrome (I have not tried it in FFX).

We could take a more targetted approach, and turn autocomplete off on fields which we know to be problematic, like `oa_statement`.

**Comment by richard-jones** [comment]
One other useful resource: https://html.spec.whatwg.org/multipage/form-control-infrastructure.html#autofill

I think the answer here is that browsers really want this to be down to users to control, but in the process they have built an autocomplete system which is not really very good, at least when it comes into contact with a complex form like ours.  That puts us in an essentially impossible position, and the best we can probably do is experiment with different autocomplete and field names to see if we can avoid erroneous offers of autocomplete.  That could be time consuming, so would be good to talk about it before doing more.

**Comment by richard-jones** [comment]
This PR is no longer relevant, superseded by the new form, so closing

**Pull request closed without merging**
