### PR TITLE
Hotfix/2017 06 10 iss1293 associate privileges

### PR DESCRIPTION
**Pull request by Steven-Eardley**
* Editor and associate editor forms throw errors when application is trying to be saved in a status outwith their editorial permissions, or backwards in the editorial pipeline.
* Editors and associate editors only see statuses that they can change to on the application edit form. Statuses beyond their permitted are visible but greyed out.

In light of the second point, the FormContextExceptions are a little redundant, because users don't get access to the statuses for the UI, but this is more complete (since the UI can be bypassed). The tests reflect this.

This may need to go on the test server so I can prove that some of my weirder code works as intended.
#1293

### CODE REVIEW

**Comment by emanuil-tolev** [comment]
> It should also, as an enhancement to the current functionality, disable the save buttons when the user is not allowed to edit the item

Is this worth a red flash message at the top of the page too?

**Comment by emanuil-tolev** [comment]
> It should also, as an enhancement to the current functionality, disable the save buttons when the user is not allowed to edit the item
> Is this worth a red flash message at the top of the page too?

Oh that is what you are suggesting

> We also need to display some text when the user is not allowed to edit an item: status accepted and rejected.

, ignore me.

**Comment by Steven-Eardley** [comment]
@emanuil-tolev ready for another review - the save buttons are disabled, and a warming is shown when editors can't edit.

**Comment by Steven-Eardley** [comment]
This is merged to production, but not deployed via fabric. That's ```git flow```'s fault.

**Pull request closed without merging**
