### PR TITLE
[hotfix] expose API and make auth information for API easier to find

### PR DESCRIPTION
**Pull request by emanuil-tolev**
# Hotfix, do not merge here

Make the API link public, fix API base URL to be the right one and put in a few sentences about auth which are a bit more specific and lead to the right area now.

### CODE REVIEW

**Comment by richard-jones** [comment]
Apparently the build failed, although I can't see from a quick peek at the code what would have caused that

**Comment by Steven-Eardley** [comment]
I think this is failing the build because the API feature is disabled, so it can't reach those routes. Because this is based on ```production``` and not ```develop```, it doesn't have the adjustments I made to the tests to activate all features (in the commit here https://github.com/DOAJ/doaj/commit/26376f88b9ba2c50fa6c184a77abb16af0a1c5cb) to pass the API tests.

**Comment by Steven-Eardley** [comment]
:+1: to your changes; But be aware, cherrypicking this commit means we'll also be releasing my changes to the API error handler code. This has been reviewed before, and should improve the error messages for the Discovery API that's been released, so I'll go ahead and release the hotfix now.

**Comment by emanuil-tolev** [comment]
> But be aware, cherrypicking this commit means we'll also be releasing my changes to the API error handler code

Yep, that's what I thought but it looked like the errors would continue to be raised, so why not.

Thanks for releasing!

**Pull request merged**
