### PR TITLE
journalcsv: Reinstated subject column and updated heading for open_ac…

### PR DESCRIPTION
**Pull request by Steven-Eardley**
…cess

# HOTFIX

Made tests pass again, renamed to test_journalcsv. Formatting improvements.
Issue #790

### CODE REVIEW

**Comment by Steven-Eardley** [comment]
@emanuil-tolev I'm happy to release this tonight with the (now ancient) PR #850 and your #855 after you've given your blessing.

**Comment by emanuil-tolev** [comment]
You changed a column and renamed a test?! Well I never

**Comment by emanuil-tolev** [comment]
:+1: of course

**Comment by emanuil-tolev** [comment]
let me know if you have any problems integrating the 3 hotfixes - shouldn't do judging by them but still

**Pull request merged**
