### PR TITLE
Update new logo, colours, brand

### PR DESCRIPTION
**Pull request by sssoz**
Done as part of DOAJ/doajPM#2933

@Steven-Eardley Could you deploy this on test tomorrow as soon as you can, so that @dommitchell and Louise can see it? Let me know if it’s not possible (I’ve already provided them with a screenshot but I figured it was better if they could click around).

### CODE REVIEW

**Review by richard-jones — APPROVED** [review]
I've reviewed this from a technical perspective, it all looks fine.  I haven't actually looked at it to see if it looks right, so still needs to go through the test server.

**Comment by dommitchell** [comment]
> I've reviewed this from a technical perspective, it all looks fine. I haven't actually looked at it to see if it looks right, so still needs to go through the test server.

Right! This isn't to go on the live site yet.

**Comment by sssoz** [comment]
@richard-jones Thank you -- yes, Louise and Dom need to take a look first anyway and we’re not quite ready to reveal the new colours & logo :) 

I’ve added one commit which simply reordered the colours in the background background here: https://github.com/DOAJ/doaj/pull/1924/commits/c346e6fe11e8c95596bc62c739baa769251e5a52

**Comment by sssoz** [comment]
Thanks for putting this on test. A few things I noticed & need to fix before we merge: 

- [ ] "Hide this message" cookie notice button text no longer visible 
- [ ] Need to update the preview images (OpenGraph + Twitter cards) 
- [ ] On mobile: background patterns should be even lighter, too bright and distracting with the text on top
- [ ] On mobile: header nav is now a bit too big
- [ ] On mobile: remove bottom border below "Funding" section 
- [ ] Sans serif font on blog headings is a bit difficult to read
- [ ] Blog should only show 6 most recent news items, not 9
- [ ] On mobile: section padding on homepage is a bit too large

**Comment by amdomanska** [comment]
May I ask: from your presentation I understood that DOAJ is going to gain more colors and that logo is going to have orange shades. On the branch on the test server, the logo is only white and I cannot see that nice colorful pattern. Is it like this on purpose?

**Comment by sssoz** [comment]
@amdomanska This is what you should be seeing 

Screenshot 2021-06-14 at 19 39 05

**Comment by sssoz** [comment]
> * Blog should only show 6 most recent news items, not 9

Done all of my own TODOs mentioned earlier today, except this one. I’ve changed the number of news items displayed in [`settings.py`](https://github.com/DOAJ/doaj/pull/1924/files#diff-954090c687b676ce7f5b7106f0265ea97df38fbdd2138c0da180f6fe3e73d61aR802) and only six are displayed locally but it’s not shown that way on test.

**Comment by sssoz** [comment]
Added a few CSS fixes (see DOAJ/doajPM#2933), needs to be re-deployed when you can, @Steven-Eardley.

**Comment by Steven-Eardley** [comment]
Re-deployed to test 2021-06-23

**Review by Steven-Eardley — APPROVED** [review]
Looks great. Right now on the test server the widgets still have the old styles, which is as intended since we haven't run re-generation yet. I'll run that and add to the release if successful

**Comment by Steven-Eardley** [comment]
@sssoz I've found a minor issue with the 'login to apply' notification (when you access the application form unauthenticated then login when prompted)
Screenshot from 2021-06-30 17-11-58

**Comment by sssoz** [comment]
> @sssoz I've found a minor issue with the 'login to apply' notification (when you access the application form unauthenticated then login when prompted)

Ah sorry, I missed this comment somehow. I can look at it now and push it on this branch! Thanks

**Comment by Steven-Eardley** [comment]
@sssoz Looks good on the applicaiton form but that's put the notification a bit low on the main page:

image

**Comment by sssoz** [comment]
> @sssoz Looks good on the applicaiton form but that's put the notification a bit low on the main page:
> 
> image

:| Done again, works for both homepage + secondary pages! Sorry

**Pull request closed without merging**
