### PR TITLE
Rebuild assets

### PR DESCRIPTION
**Pull request by sssoz**
...forgot to do it for the Paypal form in static  contents.

### CODE REVIEW

**Review by richard-jones — APPROVED** [review]
@Steven-Eardley do we rebuild assets anyway when we deploy?

**Comment by Steven-Eardley** [comment]
yes, I do the static page build on deploy, perhaps I missed this one or merged this branch in after I'd done the release branch's build.

**Comment by Steven-Eardley** [comment]
I'm going to have to close this unmerged because `git flow` doesn't like resurrecting branches (tag already exists) I'll do the build on a different hotfix branch.

**Comment by sssoz** [comment]
> resurrecting

🧟‍♀️

**Pull request closed without merging**
