### PR TITLE
Feature/3525 edit notes

### PR DESCRIPTION
**Pull request by philipkcl**
correct branch name for:
* https://github.com/DOAJ/doaj/pull/2222

https://github.com/DOAJ/doajPM/issues/3525

Note: changes to project requirements - install for running tests with `pip install -e .[test]` to get bs4/beautifulsoup

# Make notes editable by the user that created them or an admin

*Please don't delete any sections when completing this PR template; instead enter **N/A** for checkboxes or sections which are not applicable, unless otherwise stated below*

See
* https://github.com/DOAJ/doajPM/issues/3525

Describe the scope/purpose of the PR here in as much detail as you like

## Categorisation

This PR...
- [ ] has scripts to run
- [ ] has migrations to run
- [ ] adds new infrastructure
- [ ] changes the CI pipeline
- [ ] affects the public site
- [x] affects the editorial area
- [ ] affects the publisher area
- [ ] affects the monitoring

## Basic PR Checklist

Instructions for developers:
* For each checklist item, if it is N/A to your PR check the N/A box
* For each item that you have done and confirmed for yourself, check Developer box (including if you have checked the N/A box)

Instructions for reviewers:
* For each checklist item that has been confirmed by the Developer, check the Reviewer box if you agree
* For multiple reviewers, feel free to add your own checkbox with your github username next to it if that helps with review tracking

### Code Style

- No deprecated methods are used
  - [ ] N/A
  - [x] Developer
  - [x] Reviewer

- No magic strings/numbers - all strings are in `constants` or `messages` files
  - [ ] N/A
  - [x] Developer
  - [x] Reviewer
  
- ES queries are wrapped in a Query object rather than inlined in the code
  - [x] N/A
  - [ ] Developer
  - [x] Reviewer
  
- Where possible our common library functions have been used (e.g. dates manipulated via `dates`)
  - [ ] N/A
  - [x] Developer
  - [x] Reviewer
  
- Cleaned up commented out code, etc
  - [ ] N/A
  - [x] Developer
  - [x] Reviewer

### Testing

- Unit tests have been added/modified
  - [ ] N/A
  - [x] Developer
  - [x] Reviewer
  
- Functional tests have been added/modified
  - [ ] N/A
  - [ ] Developer
  - [x] Reviewer
  
- Code has been run manually in development, and functional tests followed locally
  - [ ] N/A
  - [x] Developer
  - [x] Reviewer

### Documentation

- FeatureMap annotations have been added
  - [x] N/A
  - [ ] Developer
  - [ ] Reviewer
  
- Documentation updates - if needed - have been identified and prepared for inclusion into main documentation (e.g. added and highlighted/commented as appropriate to this PR)
  - [x] N/A
  - [ ] Developer
  - [x] Reviewer
  
- Core model documentation has been added to if needed: https://docs.google.com/spreadsheets/d/1lun2S9vwGbyfy3WjIjgXBm05D-3wWDZ4bp8xiIYfImM/edit
  - [x] N/A
  - [ ] Developer
  - [x] Reviewer

- Events and consumers documentation has been added if needed: https://docs.google.com/spreadsheets/d/1oIeG5vg-blm2MZCE-7YhwulUlSz6TOUeY8jAftdP9JE/edit
  - [x] N/A
  - [ ] Developer
  - [x] Reviewer
  
- The docs for this branch have been generated and pushed to the doc site (see docs/README.md for details)
  - [x] N/A
  - [ ] Developer
  - [x] Reviewer

### Release Readiness

- If needed, migration has been created and tested locally
  - [x] N/A
  - [ ] Developer
  - [x] Reviewer

- Release sheet has been created, and completed as far as is possible https://docs.google.com/spreadsheets/d/1Bqx23J1MwXzjrmAygbqlU3YHxN1Wf7zkkRv14eTVLZQ/edit#gid=1177753675
  - [ ] N/A
  - [ ] Developer
  - [x] Reviewer

- There has been a recent merge up from `develop` (or other base branch).  List the dates of the merges up from develop below
  - 2023-04-03

## Testing

List the Functional Tests that must be run to confirm this feature:

doajtest/testbook/journal_form/associate_form.yml
doajtest/testbook/journal_form/editor_form.yml
doajtest/testbook/journal_form/maned_form.yml
doajtest/testbook/new_application_form/associate_editor_form.yml
doajtest/testbook/new_application_form/editor_form.yml
doajtest/testbook/new_application_form/maned_form.yml

(just need to wait for the testbook deploy to the docs server to work and then we can replace this with the actual links)

## Deployment

What deployment considerations are there? (delete any sections you don't need)

### Configuration changes

What configuration changes are included in this PR, and do we need to set specific values for production

### Scripts

What scripts need to be run from the PR (e.g. if this is a report generating feature), and when (once, regularly, etc).

### Migrations

What migrations need to be run to deploy this

### Monitoring

What additional monitoring is required of the application as a result of this feature

### New Infrastructure

What new infrastructure does this PR require (e.g. new services that need to run on the back-end).

### Continuous Integration

What CI changes are required for this

### CODE REVIEW

**Review by richard-jones — APPROVED** [review]
Already reviewed in other PR

**Review by Steven-Eardley — APPROVED** [review]
This is very good, I've just added `bs4` as a project dependency for testing.

I like refactoring of login into `helpers`.

We're adding to the struct for journals / applications here, which I understand won't need a migration so long as we permit the field to be missing from existing records.

**Comment by philipkcl** [comment]
updated for 
* https://github.com/DOAJ/doajPM/issues/3525#issuecomment-1551444486
* https://github.com/DOAJ/doajPM/issues/3525#issuecomment-1552830893

**Comment by sssoz** [comment]
Added a commit to fix https://github.com/DOAJ/doajPM/issues/3526 —commenting here in case it needs to be updated on the test server for @dommitchell to verify

**Review by richard-jones — COMMENTED** [review]
@philipkcl some static text changes have found their way into this PR, perhaps this branch needs a merge with develop?

**Pull request closed without merging**
