### PR TITLE
Hotfix/issue 608 new static pages

### PR DESCRIPTION
**Pull request by Steven-Eardley**
issue #608.

note: this could do with more commits to input the content of the two new static pages before it goes live.

### CODE REVIEW

**Comment by emanuil-tolev** [comment]
Hmm, the code looks good of course but I think we may need to consider how Dom could add some content before we roll this out.

Worth checking out static_pages and merging the hotfix branch into it, without merging it into develop and production yet? Then we tell Dom "here edit these files", then make a new hotfix just to release the static pages branch. So the pages go live with content. Then we just delete this hotfix branch. Sound reasonable?

You should be able to merge just by git checkout static_pages and git merge {this hotfix}.

**Comment by Steven-Eardley** [comment]
That's a good way of doing it - I already left a comment in issue #608 to explain how the changes could be added to _this_ branch before the merge - it depends on what dom is more comfortable with. For now, we can just leave this PR open.

**Comment by emanuil-tolev** [comment]
@Steven-Eardley feel free to prod Dom again for this.

Also a small change to the strategy I proposed above

> Worth checking out static_pages and merging the hotfix branch into it, without merging it into develop and production yet? Then we tell Dom "here edit these files", then make a new hotfix just to release the static pages branch. So the pages go live with content. Then we just delete this hotfix branch. Sound reasonable?

Better idea?:

git checkout static_pages
git pull
git checkout -b hotfix/static_pages_608_with_content
git merge hotfix/issue_608_new_static_pages
git push

// give Dom links to the 2 new empty files in Github, in the hotfix/static_pages_608_with_content branch - just use branch switcher while viewing any file to get the right URL
// Dom edits branch hotfix/static_pages_608_with_content
// we git flow hotfix finish static_pages_608_with_content
// then delete this hotfix
// release
// take a short holiday after so much git

**Comment by Steven-Eardley** [comment]
yes! Dom has asked for them to appear in static_pages just now. I'll do the merge.

**Comment by Steven-Eardley** [comment]
Merged to static_pages. Closing this PR.

**Pull request closed without merging**
