### PR TITLE
Feature/3794 upgrade swagger

### PR DESCRIPTION
**Pull request by philipkcl**
# Upgrade Swagger UI

*Please don't delete any sections when completing this PR template; instead enter **N/A** for checkboxes or sections which are not applicable, unless otherwise stated below*

See #
* https://github.com/DOAJ/doajPM/issues/3794

Describe the scope/purpose of the PR here in as much detail as you like

## Categorisation

This PR...
- [ ] has scripts to run
- [ ] has migrations to run
- [ ] adds new infrastructure
- [ ] changes the CI pipeline
- [x] affects the public site
- [ ] affects the editorial area
- [ ] affects the publisher area
- [ ] affects the monitoring

## Basic PR Checklist

Instructions for developers:
* For each checklist item, if it is N/A to your PR check the N/A box
* For each item that you have done and confirmed for yourself, check Developer box (including if you have checked the N/A box)

Instructions for reviewers:
* For each checklist item that has been confirmed by the Developer, check the Reviewer box if you agree
* For multiple reviewers, feel free to add your own checkbox with your github username next to it if that helps with review tracking

### Code Style

- No deprecated methods are used
  - [ ] N/A
  - [x] Developer
  - [ ] Reviewer

- No magic strings/numbers - all strings are in `constants` or `messages` files
  - [ ] N/A
  - [x] Developer
  - [ ] Reviewer
  
- ES queries are wrapped in a Query object rather than inlined in the code
  - [x] N/A
  - [ ] Developer
  - [ ] Reviewer
  
- Where possible our common library functions have been used (e.g. dates manipulated via `dates`)
  - [x] N/A
  - [ ] Developer
  - [ ] Reviewer
  
- Cleaned up commented out code, etc
  - [ ] N/A
  - [x] Developer
  - [ ] Reviewer

- Urls are constructed with `url_for` not hard-coded
  - [x] N/A
  - [ ] Developer
  - [ ] Reviewer
### Testing

- Unit tests have been added/modified
  - [x] N/A
  - [ ] Developer
  - [ ] Reviewer
  
- Functional tests have been added/modified
  - [x] N/A
  - [ ] Developer
  - [ ] Reviewer
  
- Code has been run manually in development, and functional tests followed locally
  - [ ] N/A
  - [x] Developer
  - [ ] Reviewer

- Have CSS/style changes been implemented?  If they are of a global scope (e.g. on base HTML elements) have the downstream impacts of the change in other areas of the system been considered?
  - [x] N/A
  - [ ] Developer
  - [ ] Reviewer

### Documentation

- FeatureMap annotations have been added
  - [x] N/A
  - [ ] Developer
  - [ ] Reviewer
  
- Documentation updates - if needed - have been identified and prepared for inclusion into main documentation (e.g. added and highlighted/commented as appropriate to this PR)
  - [ ] N/A
  - [x] Developer
  - [ ] Reviewer
  
- Core model documentation has been added to if needed: https://docs.google.com/spreadsheets/d/1lun2S9vwGbyfy3WjIjgXBm05D-3wWDZ4bp8xiIYfImM/edit
  - [x] N/A
  - [ ] Developer
  - [ ] Reviewer

- Events and consumers documentation has been added if needed: https://docs.google.com/spreadsheets/d/1oIeG5vg-blm2MZCE-7YhwulUlSz6TOUeY8jAftdP9JE/edit
  - [x] N/A
  - [ ] Developer
  - [ ] Reviewer
  
- The docs for this branch have been generated and pushed to the doc site (see docs/README.md for details)
  - [x] N/A
  - [ ] Developer
  - [ ] Reviewer

### Release Readiness

- If needed, migration has been created and tested locally
  - [x] N/A
  - [ ] Developer
  - [ ] Reviewer

- Release sheet has been created, and completed as far as is possible https://docs.google.com/spreadsheets/d/1Bqx23J1MwXzjrmAygbqlU3YHxN1Wf7zkkRv14eTVLZQ/edit
  - [x] N/A
  - [ ] Developer
  - [ ] Reviewer

- There has been a recent merge up from `develop` (or other base branch).  List the dates of the merges up from develop below
  - 2024-02-15

## Testing

List the Functional Tests that must be run to confirm this feature

1. ...
2. ...

## Deployment

What deployment considerations are there? (delete any sections you don't need)

### Configuration changes

What configuration changes are included in this PR, and do we need to set specific values for production

### Scripts

What scripts need to be run from the PR (e.g. if this is a report generating feature), and when (once, regularly, etc).

### Migrations

What migrations need to be run to deploy this

### Monitoring

What additional monitoring is required of the application as a result of this feature

### New Infrastructure

What new infrastructure does this PR require (e.g. new services that need to run on the back-end).

### Continuous Integration

What CI changes are required for this

### CODE REVIEW

**Review by richard-jones — APPROVED** [review]
This is a big improvement.  For me this is fine, and I would like to ask @amdomanska to have a look at it from a styles perspective, make sure that everything lines up with other documentation pages.  I will put some notes in the main issue.

**Review by amdomanska — CHANGES_REQUESTED** [review]
I have added my comment [here](https://github.com/DOAJ/doajPM/issues/3794#issuecomment-1981563640). Some tweaks are needed to ensure the style consistency with the rest of the website and DOAJ brand.

**Comment by amdomanska** [comment]
Changes implemented, available to review here:
https://github.com/DOAJ/doaj/pull/2353/files/ac790faf7b02500835568d7ea2c7a2c0820c0586..7bbd4a06d8dca231144c173d8edb1004099768e8
@richard-jones @philipkcl 
image

**Review by richard-jones — CHANGES_REQUESTED** [review]
In general the latest changes look good, there's just one technical issue which I'd like to resolve (this might turn out to be general on the site!).

When you select one of the side-nav options, it scrolls to the correct location, but because of the sticky header, the actual header for the section you've scrolled to is not visible.  See this screenshot for an example:
  
Screenshot from 2024-04-04 11-18-38

There's a secondary question about the section titles, I think that they could make more sense, will propose some alternative titles for @dommitchell to consider in the main issue.

**Comment by amdomanska** [comment]
@richard-jones 
> When you select one of the side-nav options, it scrolls to the correct location, but because of the sticky header, the actual header for the section you've scrolled to is not visible.

You're right, this is a general issue (at least for all Documentation sites). I'll see if I'm able to find a general solution, if not I will make it the dumb way for the Documentation sites.

I'll change the titles at the same time.

**Comment by richard-jones** [comment]
This PR has been merged with https://github.com/DOAJ/doaj/pull/2267 so I'm closing this one off

**Pull request closed without merging**
