### PR TITLE
Added samesite security for cookies

### PR DESCRIPTION
**Pull request by RK206**
Added samesite configuration for cookies to be secure  #1872

### CODE REVIEW

**Review by richard-jones — APPROVED** [review]

**Comment by RK206** [comment]
Updated app.py as the user cannot  login after these changes in http mode. Added ssl_context so that app will run in https mode in development

**Comment by richard-jones** [comment]
Does that mean we'll need to set up our local instances to run under https now?

**Comment by RK206** [comment]
Yes, app.py has been updated to run the app in  https mode. So the  app will run in  https mode by default in development.

**Comment by richard-jones** [comment]
ok, before we merge this, can we go through the steps that we need to do locally to make sure we can continue to develop (I'm a bit vague on using https locally)

**Comment by RK206** [comment]
Reverted the changes as per the discussion in technical meeting.
Developers should add the following configuration in dev.cfg to skip cookie security.
SESSION_COOKIE_SAMESITE=None
SESSION_COOKIE_SECURE=False
REMEMBER_COOKIE_SECURE=False

**Pull request merged**
