### PR TITLE
Feature/1470 home and sponsors

### PR DESCRIPTION
**Pull request by Steven-Eardley**
Sponsor changes for https://github.com/DOAJ/doajPM/issues/1470

### CODE REVIEW

**Comment by Steven-Eardley** [comment]
@dommitchell At the point I merge this code, the sponsors will be removed from the front page, and all of those on the sponsors page will be under the heading 'silver sponsors'. Are you ready for this to be released today?

I'll then bring static pages up to date, which would give you the ability to move the sponsors into their categories in the file ```portality/app.py```

**Comment by dommitchell** [comment]
I have to leave the office at 2pm UK today. Might be better to wait until
tomorrow morning. Can you do it say at 9am UK tomorrow?

**Comment by dommitchell** [comment]
Ps there are unreleased changes to static pages awaiting to be released.
(Don't worry: we didnt notify you yet.) Will they go live too?

On 1 Feb 2018 13:37, "Dominic Mitchell" <dom@doaj.org> wrote:

I have to leave the office at 2pm UK today. Might be better to wait until
tomorrow morning. Can you do it say at 9am UK tomorrow?

**Comment by Steven-Eardley** [comment]
> Ps there are unreleased changes to static pages awaiting to be released.
(Don't worry: we didnt notify you yet.) Will they go live too?

These have been released today (1st Feb).

> Can you do it say at 9am UK tomorrow?
That I can, I'll let you know when I've started. Will you want to make any changes to which sponsors are in which tier before it goes live?

**Comment by dommitchell** [comment]
> That I can, I'll let you know when I've started. Will you want to make any changes to which sponsors are in which tier before it goes live?

Yes, I think that we will. Where can I access the page? I don't have access here: https://github.com/DOAJ/doaj/tree/static_pages/portality/templates/doaj

**Comment by Steven-Eardley** [comment]
@dommitchell These changes are now in the ```develop``` branch waiting to go live. You can make changes to the sponsor tiers in the file https://github.com/DOAJ/doaj/blob/develop/portality/app.py#L82

but they're not ```on static_pages``` yet since that's based on the production branch.

**Comment by dommitchell** [comment]
changes made. thank you!

**Pull request closed without merging**
