### PR TITLE
[hotfix] modify gunicorn settings slightly to help with processing larger requests

### PR DESCRIPTION
**Pull request by emanuil-tolev**
At least until we reduce the processing time for those reqs. #1313

### CODE REVIEW

**Comment by emanuil-tolev** [comment]
Ping :)

**Comment by emanuil-tolev** [comment]
> Will changing the gunicorn process name on test require changes to any deployment scripts?

Nope, it's not used anywhere. Supervisor manages that process, but AFAIK it uses pid files, not names.

**Comment by emanuil-tolev** [comment]
EDIT: The reason for it was to be able to grep for it more easily.

**Comment by emanuil-tolev** [comment]
I'm busy on sth else today but will finish and deploy tomorrow (unless done first by sbd else - but no huge rush)

**Comment by Steven-Eardley** [comment]
I'll give it a wee deploy today, then!

**Comment by Steven-Eardley** [comment]
Deployed.

**Pull request closed without merging**
