### PR TITLE
Feature/issns for alt title

### PR DESCRIPTION
**Pull request by Steven-Eardley**
* searching for a jtitle will fall-back to trying alternative_title, to handle some title translations.
* show correct vol/issue using stitle, since issns_for_title now also accepts alternative_title so volume queries work.

### CODE REVIEW

**Comment by emanuil-tolev** [comment]
Not sure if it would have been useful for this open url work but there is a method called q2obj in the dao. Instead of all the checks against results['hits'] key. May not be applicable though since I see _type checks too.

**Comment by emanuil-tolev** [comment]
Leaving open aince best released as hotfix now that that project is done. But +1, feel free to release as hotfix if you get to it before me.

**Comment by richard-jones** [comment]
ok, so this is good to merge?  But just needs to be re-issued as a hotfix?  Who is in charge of this one now?

**Comment by emanuil-tolev** [comment]
> ok, so this is good to merge? But just needs to be re-issued as a hotfix? Who is in charge of this one now?

I'll just convert it to a hotfix locally and roll out I think.

**Comment by emanuil-tolev** [comment]
Rolled out.

**Pull request merged**
