### PR TITLE
Hotfix/2020 11 15 2567 script delete users without journals

### PR DESCRIPTION
**Pull request by Steven-Eardley**
Delete users script and tests for issue https://github.com/DOAJ/doajPM/issues/2567

[edited for enhancements below]

To run non-destructively use the `-r` option and supply a filename for the CSV of accounts that will be deleted.

Run again with `-i` with the same filename to be prompted to delete the user accounts. CSV should still contain header rows but user rows can be deleted from CSV if they are to be retained in the system

### CODE REVIEW

**Comment by Steven-Eardley** [comment]
This will need to be ported to the af_redesign branch before release separately.

**Comment by Steven-Eardley** [comment]
I might've thought of a modification that might improve this - rather than adding on the CSV report as an extra, the CSV report should be fed back in to perform the deletes. That way you could edit the CSV to remove accounts you want to keep.

Quicker and dirtier would be to add an exception list of user IDs if there are any accounts in the list that should be retained.

However, If they're all to be deleted every time, what's here should suffice.

**Comment by dommitchell** [comment]
> rather than adding on the CSV report as an extra, the CSV report should be fed back in to perform the deletes. That way you could edit the CSV to remove accounts you want to keep.

Is this in light of my comment here: https://github.com/DOAJ/doajPM/issues/2567#issuecomment-725302602

**Comment by Steven-Eardley** [comment]
> Is this in light of my comment here: DOAJ/doajPM#2567 (comment)?

Yep. I think I'll go ahead and make that enhancement since we'll be using the script on an ongoing basis - it may as well be customisable. It's about half an hour's work

**Comment by Steven-Eardley** [comment]
CSV read-in enhancement is done, cheers to @DhileasHeywood for the help

**Comment by Steven-Eardley** [comment]
I've added further checks for applications in the system before account deletion. On my system (not up-to-date) that resulted in ~200 accounts been retained: 540 deletes down from 740

**Review by richard-jones — APPROVED** [review]

**Pull request closed without merging**
