### PR TITLE
change css

### PR DESCRIPTION
**Pull request by amdomanska**
Fixes: https://github.com/DOAJ/doajPM/issues/2213

Tested on Chrome and Firefox on Ubuntu

Screenshot from 2019-11-04 11-53-52

### CODE REVIEW

**Comment by Steven-Eardley** [comment]
Testing on Mac:

Safari Version 13.0.3 (14608.3.10.10.1)
Screenshot 2019-11-04 at 13 56 50
Screenshot 2019-11-04 at 13 57 01

Firefox 71.0b6 looked good.

I tested Edge and Firefox on Windows and both look good.

**Comment by Steven-Eardley** [comment]
Safari with system light theme applied:

Screenshot 2019-11-04 at 14 12 48
Screenshot 2019-11-04 at 14 12 17

**Comment by amdomanska** [comment]
I moved the new style code to our doaj.css and alongside I changed the background colour of the date picker header to DOAJ orange.

Screenshot from 2019-11-04 20-21-16

**Comment by amdomanska** [comment]
released today at 11am

**Pull request closed without merging**
