### PR TITLE
Fixed timestamp returned by discovery API to be ISO-8601 compatible

### PR DESCRIPTION
**Pull request by Steven-Eardley**
Replaced timestamp line to use `dates` in `portality.lib`:

```python
def now_with_microseconds():
    return format(datetime.utcnow(), format="%Y-%m-%dT%H:%M:%S.%fZ")
```
Additional code style changes.

Note, this is a **BREAKING CHANGE** to the API since users may have created integrations with the dodgy timestamp format. Is a new version required?

timestamp format bug was reported here:
https://github.com/ropensci/jaod/issues/10

### CODE REVIEW

**Comment by katrinleinweber** [comment]
Thanks for this fix :-) It doesn't seem urgent, so how about following [semver.org's advice of introducing a deprecation warning in vX.Y.Z and then changing the behaviour in vX+1.0.0](https://semver.org/#how-should-i-handle-deprecating-functionality)?

**Comment by katrinleinweber** [comment]
OTOH, given that [this bug went unreported for 4 years](https://github.com/DOAJ/doaj/blame/8567e803fdd525ae8053aacb7a33cdca4882798d/portality/api/v1/discovery.py#L241-L249), either:

a) nobody relied on that output, and therefore no big fuzz is necessary, or 
b) people did rely on it, invested extra time in a workaround instead of reporting the bug, and therefore deserve no special care now ;->

**Comment by katrinleinweber** [comment]
Since it's also been several years since #516, and neither #735, nor #787 add a second argument for the `timestamp`, could its necessity maybe be re-evaluated in general? Do people still need to be told the time that their query was answered?

**Comment by richard-jones** [comment]
Ah, an old typo, by the looks of it.

I'm in two minds about just deploying this.  it is, as you say, a breaking change, though I would guess that no one has ever parsed that date, otherwise they would have noticed that it was skew.  My inclination would be to deploy it as is, without any warning or deprecations.  We don't make any claims anywhere as to the format of this date, it's just a string, so anyone's date parsing ought to be robust enough to handle it.

**Comment by sckott** [comment]
we don't parse the `timestamp` field in the R client, so not a breaking change for the client at least; I've no idea what our users do though.

**Comment by katrinleinweber** [comment]
Thanks for fixing this. Assuming from a lack of [reactions](https://github.com/search?q=language%3Ar+jaod+-repo%3Acran%2Fjaod+-repo%3Aropensci%2Fjaod&type=Code) [elsewhere](https://github.com/search?q=language%3Ar+doaj+-repo%3Acran%2Fjaod+-repo%3Aropensci%2Fjaod&type=Code) There seem to have been no adverse effects :-)

**Pull request closed without merging**
