### PR TITLE
Add downloadable Seal logo

### PR DESCRIPTION
**Pull request by sssoz**
...and remove unused image assets. 

See DOAJ/doajPM#3141. 

As mentioned in the [comment thread](https://github.com/DOAJ/doajPM/issues/3141#issuecomment-998301939), the [JS for showing a modal containing the HTML snippet](https://github.com/DOAJ/doaj/pull/2032/commits/cdf5493e9aa861231b967d39af23c29ac89d332e) for "embedding" the Seal was done pretty quickly and will require some cleanup. 

For example, the modal is now static — it keeps displaying the same ISSN for all journals on a single page. I would need a bit of a hint or some help to help me figure out how to do it properly!

### CODE REVIEW

**Review by richard-jones — DISMISSED** [review]
At least some of the images that have been removed are still in use in the admin area.  I haven't checked them all, but the Creative Commons images are used by the admin search interfaces.  We'll need a more comprehensive search on the codebase to make sure that the removed images can actually be removed.

I'm working on an updated version of the code for injecting the seal into the actions section of the search results, which I'll push shortly.

**Review by richard-jones — COMMENTED** [review]
I have now pushed a change which separates the seal logo display from the public search results renderer, so it can be passed in as an option.

**Comment by sssoz** [comment]
@richard-jones I’ve dropped the commits where I deleted the image files (and moved them to a new branch, `feature/remove-unused-assets`.

Just one more thing: the URL (containing the journal’s ISSN) still only displays the first Seal-awarded journal’s ISSN instead of looping over all of them for each journal. I think it’s because it’s only creating a single modal, rather than a separate modal for each journal, is that correct? 

Look at Frontiers Repositories’ publisher account for example: 

Screenshot 2021-12-21 at 11 33 50

All of the "Display Seal" modals display the same URL.

**Comment by sssoz** [comment]
Updated with changes requested by @dommitchell in https://github.com/DOAJ/doajPM/issues/3141#issuecomment-1008726513

**Comment by sssoz** [comment]
@richard-jones [https://github.com/DOAJ/doaj/pull/2032#issuecomment-998706509](this) remains an issue before we can merge this PR

**Comment by richard-jones** [comment]
Dropping those commits may have slightly confused the merge when I pulled your latest code, so I'll need you to check that the result is correct.  The PR suggests that "Download the Seal" is the correct text, but the screen shot says "Display Seal" and I wasn't sure which was the correct one.

In the mean time, I'm working on the modal thing, I'm not sure why it's happening, but I'll sort it out

**Comment by sssoz** [comment]
Just confirming that this looks good :)

**Comment by richard-jones** [comment]
@sssoz fixed that modal issue - all the modals had the same id, so only the first one was getting opened. If you could review the latest changes and make sure everything looks correct then this can be passed to @Steven-Eardley for deploy

**Comment by sssoz** [comment]
@richard-jones Looks good! Thank you.

**Review by richard-jones — APPROVED** [review]
I think the code portion of this is fine.  I see that all the removed/added image files are back, and I haven't reviewed those

**Comment by sssoz** [comment]
@richard-jones  
>  I see that all the removed/added image files are back, and I haven't reviewed those

Weird! I might have accidentally re-pushed some old commits... Let me push this again.

**Pull request closed without merging**
