### PR TITLE
Feature/735 escape slash

### PR DESCRIPTION
**Pull request by richard-jones**
Escapes all / characters in incoming search strings if they are not already escaped

### CODE REVIEW

**Comment by emanuil-tolev** [comment]
So, happy to merge as-is, but wondering if it's easy to write a test as well? Like save an article with a doi, then search for it and, well, get the result back. But can leave out if it's more than very straightforward.

**Comment by richard-jones** [comment]
Yes, wise, especially as in the process of looking at a test I found a bug

**Comment by richard-jones** [comment]
Ok, tests in - fun with layers of escape characters.

**Comment by emanuil-tolev** [comment]
Wow, that's pretty subtle with the regex overlapping matches.

Does the ```http:``` test you've added also mean that people can't put in ```:``` colon into searches then? I'll add that to the docs if so.

**Comment by richard-jones** [comment]
Yes, that's right, the ":" has special meaning so we can't trivially escape it automatically, so users will just have to be aware of what they're doing.  If they read the lucene docs it should be obvious what would happen if you put in a URL, but it could well be worth giving an example, since URL search might be something people will want to do.

**Pull request merged**
