### PR TITLE
add filter to public search results to strip out unwanted fields

### PR DESCRIPTION
**Pull request by richard-jones**
hotfix

### CODE REVIEW

**Comment by richard-jones** [comment]
Incidentally, all unit tests pass locally, so something wrong with the codeship here, I think.

**Comment by emanuil-tolev** [comment]
:+1: but can't roll out today myself I'm afraid

**Comment by Steven-Eardley** [comment]
I can deploy it today, and I'll check the build on codeship shortly.

**Comment by Steven-Eardley** [comment]
Codeship was failing due to SSH keys being denied. Maybe they've changed them. Anyway, I've set it to authenticate through my account rather than emanuil's and the builds are working again.

**Pull request merged**
