### PR TITLE
Display links to ISSN Portal records on journal TOCs

### PR DESCRIPTION
**Pull request by sssoz**
See DOAJ/doajPM#2794

### CODE REVIEW

**Review by richard-jones — APPROVED** [review]
Code wise this is fine, just wondering what happens if the record isn't in ROAD, and if that's even possible?

**Comment by sssoz** [comment]
If a non-existent ISSN is input, it’ll just tell the user that this ISSN is not on ROAD, which is fine. @dommitchell

**Comment by dommitchell** [comment]
Not possible for an ISSN to be in DOAJ and not in the Portal.

**Comment by sssoz** [comment]
@Steven-Eardley Updated text, good to go

**Pull request closed without merging**
