### PR TITLE
First pass of article page, based on the current journal template. Issue...

### PR DESCRIPTION
**Pull request by Steven-Eardley**
...s #559, #540.
May require more thought into the design and required fields.

Once this is merged, @emanuil-tolev can add his metadata stuff.

Sorry for the whitespace at the end of the html file.

### CODE REVIEW

**Comment by emanuil-tolev** [comment]
@richard-jones @Steven-Eardley was wondering whether the new article page shouldn't follow the design of the new journal (TOC) page, which has not been written yet pending mine and @markmacgillivray's changes to the journal TOC back-end and URL routing :). Something to discuss next meeting p'raps.

**Comment by emanuil-tolev** [comment]
(So for now I think @Steven-Eardley's gone for a basic design, correct me if wrong)

**Comment by emanuil-tolev** [comment]
Looks good :+1: - not tested if it actually works locally since my repo is in a different state to do with the new infrastructure and I'm in a hurry to finish that, but it definitely does not break any current code and can thus be merged, with potential bugs to be fixed later when we can actually see the work .. working.

**Comment by Steven-Eardley** [comment]
@emanuil-tolev correct, a basic design based on ransacking the toc template.

**Pull request merged**
