### PR TITLE
add script to find articles with invalid issns

### PR DESCRIPTION
**Pull request by amdomanska**
Script from https://github.com/DOAJ/doaj/pull/2254
to run on life

### CODE REVIEW

**Comment by dommitchell** [comment]
@amdomanska was this ever run? It would be good to know how many articles we are talking about.

**Review by Steven-Eardley — CHANGES_REQUESTED** [review]
Please reinstate the `-o` parameter and argparse, same effect of a default 'out.csv' can be achieved via the `default` param, and get rid of the unnecessary `if not args.out` stuff

Just makes it easier to run on live.

**Comment by Steven-Eardley** [comment]
@dommitchell I've run this on the test server and there were quite a few results, but some minor changes required to go to live

**Comment by amdomanska** [comment]
> Please reinstate the `-o` parameter and argparse, same effect of a default 'out.csv' can be achieved via the `default` param, and get rid of the unnecessary `if not args.out` stuff
> 
> Just makes it easier to run on live.

Ooops, sorry! That's what I do for development purposes, I forgot to change it back.

**Comment by amdomanska** [comment]
@Steven-Eardley I fixed the script. Sorry for the oversight! Back to you :)

**Comment by amdomanska** [comment]
Merged with develop 5/09/23

**Review by Steven-Eardley — APPROVED** [review]

**Pull request merged**
