### PR TITLE
remove all references to addthis

### PR DESCRIPTION
**Pull request by richard-jones**

### CODE REVIEW

**Comment by Steven-Eardley** [comment]
Does this require a widget refresh?

**Comment by richard-jones** [comment]
> Does this require a widget refresh?

Yes, good point, I'll do that in a second

**Comment by richard-jones** [comment]
> > Does this require a widget refresh?
> 
> Yes, good point, I'll do that in a second

Actually, it turns out no, it doesn't need a rebuild.  The addthis feature is only on the site's facetviews not on the FQW's one.

**Comment by dommitchell** [comment]
HOORAY!

**Pull request closed without merging**
