### PR TITLE
Feature/3589 refactor paths

### PR DESCRIPTION
**Pull request by philipkcl**
# [Refactoring] extract common join method to paths

*Please don't delete any sections when completing this PR template; instead enter **N/A** for checkboxes or sections which are not applicable, unless otherwise stated below*

See #
* https://github.com/DOAJ/doajPM/issues/3589

Describe the scope/purpose of the PR here in as much detail as you like
use `portality.lib.paths` make the code more readable

## Categorisation

This PR...
- [ ] has scripts to run
- [ ] has migrations to run
- [ ] adds new infrastructure
- [ ] changes the CI pipeline
- [ ] affects the public site
- [ ] affects the editorial area
- [ ] affects the publisher area
- [ ] affects the monitoring

## Basic PR Checklist

Instructions for developers:
* For each checklist item, if it is N/A to your PR check the N/A box
* For each item that you have done and confirmed for yourself, check Developer box (including if you have checked the N/A box)

Instructions for reviewers:
* For each checklist item that has been confirmed by the Developer, check the Reviewer box if you agree
* For multiple reviewers, feel free to add your own checkbox with your github username next to it if that helps with review tracking

### Code Style

- No deprecated methods are used
  - [ ] N/A
  - [x] Developer
  - [x] Reviewer

- No magic strings/numbers - all strings are in `constants` or `messages` files
  - [ ] N/A
  - [x] Developer
  - [x] Reviewer
  
- ES queries are wrapped in a Query object rather than inlined in the code
  - [x] N/A
  - [ ] Developer
  - [ ] Reviewer
  
- Where possible our common library functions have been used (e.g. dates manipulated via `dates`)
  - [ ] N/A
  - [x] Developer
  - [x] Reviewer
  
- Cleaned up commented out code, etc
  - [ ] N/A
  - [x] Developer
  - [x] Reviewer

### Testing

- Unit tests have been added/modified
  - [ ] N/A
  - [x] Developer
  - [x] Reviewer
  
- Functional tests have been added/modified
  - [x] N/A
  - [ ] Developer
  - [x] Reviewer
  
- Code has been run manually in development, and functional tests followed locally
  - [ ] N/A
  - [x] Developer
  - [ ] Reviewer

### Documentation

- FeatureMap annotations have been added
  - [x] N/A
  - [ ] Developer
  - [ ] Reviewer
  
- Documentation updates - if needed - have been identified and prepared for inclusion into main documentation (e.g. added and highlighted/commented as appropriate to this PR)
  - [x] N/A
  - [ ] Developer
  - [x] Reviewer
  
- Core model documentation has been added to if needed: https://docs.google.com/spreadsheets/d/1lun2S9vwGbyfy3WjIjgXBm05D-3wWDZ4bp8xiIYfImM/edit
  - [x] N/A
  - [ ] Developer
  - [x] Reviewer

- Events and consumers documentation has been added if needed: https://docs.google.com/spreadsheets/d/1oIeG5vg-blm2MZCE-7YhwulUlSz6TOUeY8jAftdP9JE/edit
  - [x] N/A
  - [ ] Developer
  - [x] Reviewer
  
- The docs for this branch have been generated and pushed to the doc site (see docs/README.md for details)
  - [x] N/A
  - [ ] Developer
  - [x] Reviewer

### Release Readiness

- If needed, migration has been created and tested locally
  - [x] N/A
  - [ ] Developer
  - [x] Reviewer

- Release sheet has been created, and completed as far as is possible https://docs.google.com/spreadsheets/d/1Bqx23J1MwXzjrmAygbqlU3YHxN1Wf7zkkRv14eTVLZQ/edit
  - [x] N/A
  - [ ] Developer
  - [ ] Reviewer

- There has been a recent merge up from `develop` (or other base branch).  List the dates of the merges up from develop below
  - 2023-05-09
  - 2023-05-12

## Testing

List the Functional Tests that must be run to confirm this feature

1. ...
2. ...

## Deployment

What deployment considerations are there? (delete any sections you don't need)

### Configuration changes

What configuration changes are included in this PR, and do we need to set specific values for production

### Scripts

What scripts need to be run from the PR (e.g. if this is a report generating feature), and when (once, regularly, etc).

### Migrations

What migrations need to be run to deploy this

### Monitoring

What additional monitoring is required of the application as a result of this feature

### New Infrastructure

What new infrastructure does this PR require (e.g. new services that need to run on the back-end).

### Continuous Integration

What CI changes are required for this

### CODE REVIEW

**Comment by amdomanska** [comment]
The paths in the `ingestarticles` tests were changed but not in the code itself. For example: https://github.com/DOAJ/doaj/blob/1194194931d5b75660b91f66ae6b56018bd63f72/portality/tasks/ingestarticles.py#LL222C23-L222C23

Then changes in this file have to be followed by appropriate functional tests.

**Review by amdomanska — COMMENTED** [review]
Is it intentional that only test files were changed to use the new scheme?

The paths in the `ingestarticles` tests were changed but not in the code itself. For example: https://github.com/DOAJ/doaj/blob/1194194931d5b75660b91f66ae6b56018bd63f72/portality/tasks/ingestarticles.py#LL222C23-L222C23

Then changes in this file have to be followed by appropriate functional tests.

**Comment by philipkcl** [comment]
> Is it intentional that only test files were changed to use the new scheme?
> 
> The paths in the `ingestarticles` tests were changed but not in the code itself. For example: https://github.com/DOAJ/doaj/blob/1194194931d5b75660b91f66ae6b56018bd63f72/portality/tasks/ingestarticles.py#LL222C23-L222C23
> 
> Then changes in this file have to be followed by appropriate functional tests.

```
path = os.path.join(upload_dir, file_upload.local_filename)
```

and  appropriate in test case, is only available if first object is `pathlib.Path` type
```
PATH_RESOURCES = paths.get_project_root() / 'doajtest/unit/resources'
```

I think no need to limited developer to only use join style of `pathlib`


the purpose of refactor paths is only remove duplicate code and make sure call `portality.lib.paths` if possible.

**Review by richard-jones — APPROVED** [review]

**Review by amdomanska — APPROVED** [review]

**Review by Steven-Eardley — APPROVED** [review]
great improvement

**Pull request merged**
