### PR TITLE
Feature/1175 Bulk delete UI

### PR DESCRIPTION
**Pull request by emanuil-tolev**
#1175 

I should note this also includes work from #1203 , so #1203 would be easier to review first. Then this diff will shrink considerably to only include my UI work.

### CODE REVIEW

**Comment by emanuil-tolev** [comment]
I should note this also includes work from #1203 , so #1203 would be easier to review first. Then this diff will shrink considerably to only include my UI work.

**Comment by emanuil-tolev** [comment]
Huey needs to be restarted in its screen on doaj-test after merging this. It would be great if whoever merges it does that or leaves a comment for me to do.

**Comment by Steven-Eardley** [comment]
On test now, and Huey restarted.

**Comment by emanuil-tolev** [comment]
> I think it's worth merging this so we can at least confirm that the functionality works through the UI. If we then go on to re-structure how it is presented, that's another step. I'll give that one some thought.

Yeah this doesn't really pertain to whether we decide to simply remove the option from the menu, or only add it for technical admin staff (CL) or whatever.

**Pull request merged**
